"""Token and LLM API usage tracking for evaluation reports."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path


@dataclass
class UsageTracker:
    """Accumulates LLM API metrics and writes evaluation/usage_report.md."""

    provider: str = "OpenAI"
    model_name: str = "gpt-4o-mini"
    calls: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    requests_processed: int = 0

    _instance: UsageTracker | None = None

    @classmethod
    def get_instance(cls) -> UsageTracker:
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def record_request(self) -> None:
        """Increment processed request count."""
        self.requests_processed += 1

    def record_call(self, input_tokens: int = 0, output_tokens: int = 0) -> None:
        """Record an LLM API call and token consumption."""
        self.calls += 1
        self.input_tokens += int(input_tokens)
        self.output_tokens += int(output_tokens)

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens

    @property
    def estimated_cost(self) -> float:
        # gpt-4o-mini: $0.15 per 1M input tokens, $0.60 per 1M output tokens
        input_cost = (self.input_tokens / 1_000_000.0) * 0.15
        output_cost = (self.output_tokens / 1_000_000.0) * 0.60
        return input_cost + output_cost

    def write_report(
        self,
        report_path: Path | str = "evaluation/usage_report.md",
        run_date: str | None = None,
    ) -> Path:
        """Write or overwrite the evaluation usage report markdown file."""
        target_path = Path(report_path)
        target_path.parent.mkdir(parents=True, exist_ok=True)
        report_date = run_date or date.today().isoformat()

        req_count = max(1, self.requests_processed)
        avg_tokens = self.total_tokens / req_count
        cost_per_req = self.estimated_cost / req_count

        content = f"""# Final Full-Dataset Usage Report

Run date: {report_date}

The final `output.csv` was generated by `python code/main.py` for all {self.requests_processed}
requests using active LLM metrics for `{self.model_name}`.

| Provider | Model | Calls | Input tokens | Output tokens | Estimated cost |
| --- | --- | ---: | ---: | ---: | ---: |
| {self.provider} | {self.model_name} | {self.calls} | {self.input_tokens:,} | {self.output_tokens:,} | ${self.estimated_cost:.4f} |
| **Total** | — | **{self.calls}** | **{self.input_tokens:,}** | **{self.output_tokens:,}** | **${self.estimated_cost:.4f}** |

| Metric | Value |
| --- | ---: |
| Requests processed | {self.requests_processed} |
| Total tokens | {self.total_tokens:,} |
| Average tokens per request | {avg_tokens:.2f} |
| Total estimated cost | ${self.estimated_cost:.4f} |
| Estimated cost per request | ${cost_per_req:.6f} |
"""
        target_path.write_text(content, encoding="utf-8")
        return target_path
